{% set name = "markov_clustering" %}
{% set version = "0.0.6.dev0" %}
{% set sha256 = "eec8428ce2e68e0e611fe497f36956f6eedbbf8cd8c60339d20521f2dd6cc2fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

about:
  home: https://github.com/GuyAllard/{{ name|lower }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This module implements the MCL algorithm in python.

source:
  url: https://github.com/GuyAllard/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  host:
    - python
    - pip
  run:
    - python >=3
    - scipy >=0.19.0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

test:
  imports:
    - markov_clustering
